### PR TITLE
using a bayesian estimate paired with kelly estimate

### PR DESCRIPTION
**Pull request by williambdean**
Your Kelly Criterion video inspired me to explore using a bayesian estimation of the head probability while using the Kelly strategy. 

It uses the beta conjugate prior for the binomial model to do so. I've compared an uninformed and informed prior as well as strategies that no longer wait to collect data before betting since bayesian methods will be robust in that regard. 

Not sure if you are accepting PRs, but was wondering if you explored this at all. I also thought the comparison plot of the different strategies at the bottom might be good addition.  

Either way, thanks for the informative videos!

### CODE REVIEW

**Comment by Duane321** [comment]
Hey, sorry I missed this! I wasn't expecting any PRs here.

And this is beautiful!

image

Very cool - it's so natural to think how Bayesians would approach this problem. Nice to see that answered. Thank you - excellent stuff here.

I'll be happy to merge, but could you break this out as a separate notebook and mention something at the top of the notebook that makes it clear it's your extension? Something like "This notebook is an extension from <your github handle>.. and I wanted to do XYZ". I know you made it work nicely with what I have, but in case I get questions way down the line, I want to remember what I did and what someone else did. That's also helpful for people relating the notebooks to my videos.

Thanks again!

**Comment by williambdean** [comment]
Great. Thanks for that feedback and understood!
I will move into separate notebook and include that verbiage at the top 😄

**Comment by williambdean** [comment]
All separated now. Just reverted the original notebook back to the main branch version. 
Let me know if I missed any of your suggestions.

**Comment by Duane321** [comment]
@wd60622 Thank you! Merged :)

**Pull request merged**
